server:
  port: 8888
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.128
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
#          enabled: true
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8080
#      # 服务启动直接建立心跳连接
#      eager: true
      routes:
        - id: mall-auth
          uri: lb://mall-authcenter
          predicates:
            - Path=/oauth/**
        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/sso/**,/member/**
mall:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
