server:
  port: 8888
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.128
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: mall-auth
          uri: lb://mall-authcenter
          predicates:
            - Path=/oauth/**
        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/sso/**
mall:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
