server:
  port: 8888
spring:
  application:
    name: tulingmall-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: mall-authcenter
          uri: lb://mall-authcenter
          predicates:
            - Path=/oauth/**
        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/sso/**
tuling:
  gateway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
