server:
  port: 8866
spring:
  application:
    name: mall-auth
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/pine_mall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: pl,okmijn
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  cloud:
    nacos:
      discovery:
        serverAddr: 192.168.1.128

mybatis:
  mapper-locations:
    - classpath:/mapper/**/*Dao.xml
pine:
  jwt:
    keyPairName: jwt.jks
    keyPairAlias: jwt
    keyPairSecret: pine7711
    keyPairStoreSecret: pine7711